[manager]

prepend_keymap = [
	{ on = "Z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
	{ on = "z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
	{ on = "?", run = "help", desc = "Open help" },
	{ on = "O", run = "open", desc = "Open selected files" },
	{ on = "o", run = "open --interactive", esc = "Open selected files interactively" },
	{ on = "<S-Enter>", run = "open", desc = "Open selected files" },
	{ on = "<Enter>", run = "open --interactive", desc = "Open selected files interactively" },
]
