
# Other Homebrew packages
brew aom
brew autoconf
brew boost
brew brew-file
brew cairo
brew cmake
brew direnv
brew eigen
brew erlang
brew ffmpeg
brew fish
brew flac
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gcc
brew gd
brew gdbm
brew gettext
brew gflags
brew ghostscript
brew gibo
brew giflib
brew glib
brew glog
brew gmp
brew gnutls
brew go
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew hdf5
brew icu4c
brew ilmbase
brew isl
brew jasper
brew jemalloc
brew jpeg
brew jq
brew lame
brew leptonica
brew libass
brew libbluray
brew libevent
brew libffi
brew libidn2
brew libmpc
brew libogg
brew libpng
brew libsamplerate
brew libsndfile
brew libsoxr
brew libspiro
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libuv
brew libvorbis
brew libvpx
brew libvterm
brew libyaml
brew little-cms2
brew lua
brew luajit
brew mas
brew mecab
brew mecab-ipadic
brew mono
brew mpfr
brew msgpack
brew mysql
brew ncurses
brew neovim
brew netpbm
brew nettle
brew nkf
brew nodebrew
brew numpy
brew oniguruma
brew openblas
brew opencore-amr
brew opencv
brew openexr
brew openjpeg
brew openssl
brew opus
brew p11-kit
brew pacvim
brew pango
brew pcre
brew pcre2
brew perl
brew pixman
brew pkg-config
brew pyenv
brew pyenv-virtualenv
brew python
brew python@2
brew rabbitmq
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rtmpdump
brew rubberband
brew ruby
brew rust
brew sdl2
brew selenium-server-standalone
brew shfmt
brew snappy
brew speex
brew sqlite
brew szip
brew tbb
brew tesseract
brew theora
brew tmux
brew unbound
brew unibilium
brew vim
brew webp
brew wget
brew wxmac
brew x264
brew x265
brew xvid
brew xz
brew zsh
brew zsh-completions

# Other Cask applications
cask cool-retro-term
cask db-browser-for-sqlite
cask font-hack-nerd-font
cask java
cask oni
cask vagrant
cask virtualbox

# App Store applications
appstore 1024640650 CotEditor (3.7.6)
appstore 549083868 Display Menu (2.2.3)
appstore 682658836 GarageBand (10.3.2)
appstore 408981434 iMovie (10.1.12)
appstore 409183694 Keynote (9.0.2)
appstore 539883307 LINE (5.17.1)
appstore 748212890 Memory Diag (2.4.6)
appstore 409203825 Numbers (6.0)
appstore 823766827 OneDrive (19.070.2410)
appstore 409201541 Pages (8.0)
appstore 803453959 Slack (3.4.2)
appstore 585829637 Todoist (7.1.3)
appstore 485812721 TweetDeck (3.16.1)
