#!/usr/bin/env bash

tmpfile=$(mktemp /tmp/gitdiff-staged.XXXXXX.diff)
git --no-pager diff --staged > "$tmpfile"
if [[ -s "$tmpfile" ]]; then
  nvim -R "$tmpfile" -c 'set ft=diff'
else
  echo "staged の変更なし"
fi
rm -f "$tmpfile"
